[theme]
base = "dark"
primaryColor = "#1f77b4"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"

[server]
headless = true
address = "0.0.0.0"
port = 3000

[browser]
gatherUsageStats = false
